### ISSUE TITLE
Error 400: Invalid OAuth access token

### ISSUE THREAD

**Issue by Graba994** [emes30/facebook_messenger#2]
Logger: custom_components.facebook_messenger.notify
Source: custom_components/facebook_messenger/notify.py:136
Integration: Facebook Messenger ([documentation](https://github.com/emes30/facebook_messenger), [issues](https://github.com/emes30/facebook_messenger/issues))
First occurred: 18:16:28 (6 occurrences)
Last logged: 18:16:44

Error 400 : Invalid OAuth access token - Cannot parse access token (Code 190)

----

  name: messenger
  platform: facebook_messenger
  page_access_token: secret! token
  targets:
    - sid: 10000047666***
      name: Patrick
      
found the SID on the website : lookup-id.com
I generated the token in accordance with the instructions.
      
 why am i getting such an error?

**Comment by emes30** [comment]
> page_access_token: secret! token

should be
```yaml
page_access_token: !secret token
```
Exclamation mark goes first.
